### ISSUE TITLE
Authentication doesn't work

### ISSUE THREAD

**Issue by basemre** [anthofo/trakt-tv-duplicates-removal#1]
### Expected behavior
The link, which has been generated by script, do auth operation

### Actual behavior
The link should work

### Error logs and screenshots
![image](https://user-images.githubusercontent.com/9062254/46220492-e74b3380-c352-11e8-8716-691852c2dd03.png)

![image](https://user-images.githubusercontent.com/9062254/46220478-db5f7180-c352-11e8-97b3-8053c26259ad.png)

**Comment by anthofo** [comment]
Hi,

I tried it and it works. Please check that the redirect uri set in your trakt-tv application (https://trakt.tv/oauth/applications) is set to `urn:ietf:wg:oauth:2.0:oob`  as shown below:

![betaseries-to-trakt - trakt tv - google chrome](https://user-images.githubusercontent.com/3809685/46735031-45eaa880-cc95-11e8-8a00-13c602ce0b19.jpg)

**Comment by basemre** [comment]
Yes, it's worked.
